return {
  -- "nvimtools/none-ls.nvim",
  -- config = function()
  --   local null_ls = require("null-ls")
  --   null_ls.setup({
  --
  --     sources = {
  --       null_ls.builtins.formatting.prettier.with({
  --         filetypes = {
  --           "lua",
  --           "python",
  --           "javascript",
  --           "typescript",
  --           "javascriptreact",
  --           "typescriptreact",
  --           "css",
  --           "html",
  --           "json",
  --           "yaml",
  --           "markdown",
  --           "graphql",
  --           "php",
  --         },
  --       }),
  --     },
  --
  --     vim.keymap.set("n", "<leader>cf", vim.lsp.buf.format, {}),
  --   })
  -- end,
}
