return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    -- (Explanation) Insert your language to allow for syntax highlight and better searching using /
    ensure_installed = {
      "bash",
      "c",
      "diff",
      "html",
      "javascript",
      "typescript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      "perl",
      "php",
    },
    auto_install = true,
  },
}
